services:
  - type: web
    name: conformexpert
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: conformexpert-db
          property: connectionString
      - key: CONTACT_EMAIL
        value: "contact@conformexpert.fr"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@conformexpert.fr"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"

databases:
  - name: conformexpert-db
    plan: free
